#!/usr/bin/env php
<?php
require(__DIR__ . '/src/config/init.php');
require(__DIR__ . '/vendor/yiisoft/yii2/Yii.php');
require(__DIR__ . '/src/config/bootstrap.php');
$config = require(__DIR__ . '/src/config/main.php');
exit((new yii\console\Application($config))->run());